### ISSUE TITLE
Pull Adventurer Moves out into their own text.

### ISSUE THREAD

**Issue by blinks** [Sagelt/beyond#2]
Unless they're different per-class, then you'd want to keep them separate but probably not worth the distinction in name?

**Comment by Sagelt** [comment]
They are different per class in that each class can have different abilities and conditions for each. I'd love to still be able to single source the basic text, but each class also gets a different bonus to each adventurer move (since there are no stats), which means it'd have to be a template which is technically feasible but I'm trying to focus on writing and making sure the plain text is easy to read.
